# Generated by Django 5.2.8 on 2025-11-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Уникальное системное имя меню, например 'main_menu'", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Удобное название для редактирования меню', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('named_url', models.CharField(blank=True, help_text='Имя без аргументов', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Прямой URL (пример: /about/ или https://...)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Порядок среди соседей')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
